In [ ]:
'''
Alejandro Fernández Trigo
'''

In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# No es necesario ninguna imagen; en este ejercicio trabajamos solo con una matriz de prueba!
# imagen = cv.imread('img/10_NorthCarolina.jpg',cv.IMREAD_GRAYSCALE)

In [3]:
# Matriz de ejemplo del enunciado:
matriz_ejemplo = np.array([
    [1,1,1,3],
    [2,1,1,1],
    [3,2,1,1],
    [1,1,1,2],
])

In [4]:
# Máscara del enunciado:
mask = np.array([
    [1,0,1,1],
    [1,0,1,1],
    [1,0,1,0],
    [1,0,1,0],
])

In [5]:
# Función máscara: recibe la imagen + máscara
def mascara(img, mask):
    # Es la multiplicación simple de matrices por la izquierda:
    # resultado = img * mask
    # SOLO con la misma dimensión!
    
    # En otro caso, recorrer filas/columnas; en las posiciones
    # a cero, hacer cero el resultado:
    resultado = img.copy()
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            if mask[i][j] == 0:
                resultado[i][j] = 0
    
    return resultado

In [6]:
print("Matriz de ejemplo: \n" + str(matriz_ejemplo))
print("Matriz de ejemplo enmascarada: \n" + str(mascara(matriz_ejemplo, mask)))

Matriz de ejemplo: 
[[1 1 1 3]
 [2 1 1 1]
 [3 2 1 1]
 [1 1 1 2]]
Matriz de ejemplo enmascarada: 
[[1 0 1 3]
 [2 0 1 1]
 [3 0 1 0]
 [1 0 1 0]]
